#########################################
#
#       必填配置
#
##########################################
project_name: musegame
project_root: /data/muse/game-01/trunk/musegame

##########################################
#
#       可选配置,可根据自己需求
#
##########################################

